# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_version = "= 1.5.5"
      required_providers {
        aws = {
          version = "~> 5.0"
        }
      }
    }

    provider "aws" {
      default_tags {
        tags = {
          Project = "iac-aws-sandbox"
        }
      }
    }
